services:
  mongodb:
    image: mongo:7
    container_name: amm-training-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: amm-training
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
